import { useEffect, useRef } from "react";
import{Accordion, AccordionContent, AccordionItem, AccordionTrigger}from"../../components/ui/accordion";

const FAQSection = () => {
  const sectionRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries: IntersectionObserverEntry[]) => {
        entries.forEach((entry: IntersectionObserverEntry) => {
          if (entry.isIntersecting) {
            (entry.target as HTMLElement).classList.add('animate-fade-in-up');
          }
        });
      },
      { threshold: 0.1 }
    );

    const elements = sectionRef.current?.querySelectorAll('[data-scroll-reveal]');
    elements?.forEach((el) => observer.observe(el));

    return () => observer.disconnect();
  }, []);

  const faqs = [
    {
      question: "What is Orion and how does it utilize Story Protocol?",
      answer: "Orion is a decentralized platform built on Story Protocol, designed to empower creators with on-chain tools for registering, managing, and monetizing their intellectual property. Story Protocol provides the foundational infrastructure for IP assets, derivatives, and royalty distribution."
    },
    {
      question: "How does Orion ensure my IP's authenticity and provenance?",
      answer: "Through Story Protocol, every IP registration on Orion creates an immutable record on the blockchain. This provides verifiable proof of creation, ownership, and a transparent history of all associated licenses and derivatives."
    },
    {
      question: "Can I track derivatives of my IP on Orion?",
      answer: "Yes, Orion, powered by Story Protocol, offers robust derivative tracking. When a new work is identified as a derivative of your IP, it can be linked on-chain, automatically setting up royalty flows for the original creator."
    },
    {
      question: "How are royalties distributed for my IP on Orion?",
      answer: "Royalties are automatically distributed via Story Protocol's royalty module. Once your IP is registered and licensed, any revenue generated by your original or derivative works is split and paid out to all eligible rights holders according to pre-defined terms."
    },
    {
      question: "Is Orion designed for all types of creators and intellectual property?",
      answer: "Orion is built to support a wide range of creative IPs, from digital art and music to written works and real-world assets. Our platform provides a flexible framework for creators across various industries to manage and monetize their unique intellectual property."
    }
  ];

  return (
    <section id="faqs" ref={sectionRef} className="py-24 bg-[#f6fbff] relative">
      <div className="max-w-[1200px] mx-auto px-6">
        {/* Floating Card Component - Matching Integration Section Style */}
        <div 
          className="bg-[#d8dfe5] rounded-[20px] p-12 md:p-16 card-shadow relative opacity-0"
          data-scroll-reveal
          style={{ 
            boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
            animationDelay: '0.2s'
          }}
        >
          <div className="text-center mb-16">
            <div className="inline-block bg-white/80 backdrop-blur-sm rounded-full px-4 py-2 text-sm font-medium text-gray-700 mb-6">
              FAQ
            </div>
            <h2 className="font-['Plus_Jakarta_Sans'] mb-2 text-[#0e1c29] text-[44px] not-italic font-normal h-[52.8px] tracking-[-0.44px] leading-[52.8px]">
              Your Orion Questions, Answered.
            </h2>
            <p className="font-inter text-base md:text-lg text-[#0e1c29]/80 max-w-2xl mx-auto mt-4">
              Everything you need to know about Orion, Story Protocol, and on-chain IP management.
            </p>
          </div>

          <div className="max-w-3xl mx-auto opacity-0" data-scroll-reveal style={{ animationDelay: '0.4s' }}>
            <Accordion type="single" collapsible className="space-y-4">
              {faqs.map((faq, index) => (
                <AccordionItem 
                  key={`faq-${index}`} 
                  value={`item-${index}`}
                  className="bg-white/80 backdrop-blur-sm rounded-2xl px-6 border-0"
                  style={{
                    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)'
                  }}
                >
                  <AccordionTrigger className="font-jakarta text-lg font-semibold text-[#0e1c29] hover:no-underline py-6">
                    {faq.question}
                  </AccordionTrigger>
                  <AccordionContent className="font-inter text-base text-[#0e1c29]/80 leading-relaxed pb-6">
                    {faq.answer}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FAQSection;